# PostgreSQL. Versions 8.2 and up are supported.

development: &defaults
  adapter: postgresql
  encoding: unicode
  database: theglamourist_development
  pool: 5
  host: localhost
  port: 5432

test:
  <<: *defaults
  database: theglamourist_test

production:
  <<: *defaults
  database: theglamourist_production
